### ISSUE TITLE
The plugin is good, but there is a problem, the implicit return value will not be annotated

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [siosio/kdoc-generator-intellij-plugin#3]
![image](https://user-images.githubusercontent.com/54784104/135620951-6a5efe14-ce4f-438b-a296-242dd9dcf347.png)
And I want to put the cursor on the function and use the shortcut key to insert the corresponding comment, can I? Just like java doc.

**Comment by siosio** [comment]
@SaltedFish-Extreme Fixed version 2.0.2 released.

Thanks for the bug report.

**Comment by SaltedFish-Extreme** [comment]
Ah, my as version is 4.2.2, not the latest version of Arctic Fox, it seems that the plug-in cannot be installed😢
![image](https://user-images.githubusercontent.com/54784104/135709933-c68b8caf-2e48-4125-9c6a-63e06ddf43bd.png)

**Comment by SaltedFish-Extreme** [comment]
> @SaltedFish-Extreme 已发布 2.0.2 固定版本。
> 
> 感谢您的错误报告。

In addition, I don’t know why, the first file opened when the project is opened for the first time after the plug-in is enabled will always perform code analysis and scanning, and will not check for problems and prompt messages.
![image](https://user-images.githubusercontent.com/54784104/135710542-695155c9-5765-4e89-abb8-b3e1abf5f547.png)

**Comment by siosio** [comment]
fix https://github.com/siosio/kdoc-generator-intellij-plugin/commit/2caac1ec4cff8b20f4a3a79f92563157525d1846.

version 2.0.3 released.

**Comment by SaltedFish-Extreme** [comment]
> 修复[2caac1e](https://github.com/siosio/kdoc-generator-intellij-plugin/commit/2caac1ec4cff8b20f4a3a79f92563157525d1846)。
> 
> 2.0.3 版本发布。

Ah, this seems to be the source code, I can’t directly drag and drop it into as to use😢
![image](https://user-images.githubusercontent.com/54784104/135710911-b2d93d6b-ed2e-4eef-8ff3-2147bb88ff9a.png)

**Comment by siosio** [comment]
Please click on the link below to download the file.

https://github.com/siosio/kdoc-generator-intellij-plugin/releases/download/2.0.3/kdoc-generator-2.0.3.zip

**Comment by SaltedFish-Extreme** [comment]
> 请点击以下链接下载文件。
> 
> https://github.com/siosio/kdoc-generator-intellij-plugin/releases/download/2.0.3/kdoc-generator-2.0.3.zip

Ah, there seems to be a problem... Unable to generate doc, Android Studio also reported an error

java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.types.KotlinType org.jetbrains.kotlin.idea.core.UtilsKt.resolveType(org.jetbrains.kotlin.psi.KtExpression)'
	at siosio.kodkod.NamedFunctionKDocGenerator.generate(KDocGenerator.kt:46)
	at siosio.kodkod.EnterAfterKDocGenHandler.postProcessEnter$lambda-5(EnterAfterKDocGenHandler.kt:54)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:986)
	at siosio.kodkod.EnterAfterKDocGenHandler.postProcessEnter(EnterAfterKDocGenHandler.kt:46)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteActionInner(EnterHandler.java:165)
	at com.intellij.codeInsight.editorActions.EnterHandler.lambda$executeWriteAction$0(EnterHandler.java:65)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.lambda$disablePostprocessFormattingInside$2(PostprocessReformattingAspect.java:104)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:112)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:103)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:64)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:986)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:65)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:201)
	at com.intellij.codeInsight.template.impl.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:986)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:65)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$null$2(EditorActionHandler.java:191)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$3(EditorActionHandler.java:190)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:299)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:408)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:308)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:283)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:188)
	at com.jetbrains.cidr.lang.editor.OCSmartCompletionInPlaceholderEnterHandler.executeWriteAction(OCSmartCompletionInPlaceholderEnterHandler.java:83)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:986)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:65)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
	at com.intellij.xdebugger.impl.actions.handlers.XDebuggerSmartStepIntoHandler$SmartStepEditorActionHandler.doExecute(XDebuggerSmartStepIntoHandler.java:418)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:52)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:89)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:98)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:73)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:610)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:471)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:220)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:890)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:835)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:808)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

![image](https://user-images.githubusercontent.com/54784104/135712634-50e5d5bd-831b-461f-8270-0a6c71d247d9.png)

**Comment by siosio** [comment]
fix :bug:

https://github.com/siosio/kdoc-generator-intellij-plugin/releases/download/2.0.4/kdoc-generator-2.0.4.zip

**Comment by SaltedFish-Extreme** [comment]
> fix 🐛
> 
> https://github.com/siosio/kdoc-generator-intellij-plugin/releases/download/2.0.4/kdoc-generator-2.0.4.zip

Ah, there is no problem. Thank you very much for your efforts. This plugin is very useful. I hope it can be updated in the plugin market so that more people can use the new version😃 In addition, if you can position the cursor on the method you want to annotate, use the shortcut key It would be better to generate contextual documentation comments😊
